[package]
name = "huffcompress-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.39", features = ["derive"]}
rayon = "1.10.0"
serde = {version = "1.0.219", features = ["derive"] }
bit-vec = { version = "0.6", features = ["serde"] }
rmp-serde = "1.3.0"
